// Code generated by cmd/contractgen. DO NOT EDIT.
// HTTP authorization and WebSocket transport remain owned by the host/client.

export type Api = string;

export interface AppearanceInput {
  mode: AppearanceMode;
}

export type AppearanceMode = "system" | "light" | "dark";

export interface Approval {
  id: string;
  toolName: string;
  args: unknown;
  warning?: string;
  preview?: ApprovalPreview;
}

export interface ApprovalInput {
  id: string;
  allow: boolean;
  alwaysAllow?: boolean;
}

export interface ApprovalPreview {
  path: string;
  kind: string;
  diff?: string;
  error?: string;
  truncated?: boolean;
}

export interface Artifact {
  path: string;
  name: string;
}

export interface ArtifactPreview {
  kind: string;
  text?: string;
  data?: string;
  mimeType?: string;
  truncated?: boolean;
}

export interface ArtifactQuery {
  id: string;
  path: string;
}

export interface BranchInput {
  id: string;
  nodeId: string;
  before?: boolean;
}

export interface CommandDetails {
  text: string;
  cwd: string;
  exitCode?: number;
}

export interface ConfigInput {
  provider: string;
  thinkingLevel: string;
  baseUrl: string;
  model: string;
  apiKey?: string;
  clearApiKey?: boolean;
}

export interface ConnectionTest {
  ok: boolean;
  kind: string;
  message: string;
  toolCalling: boolean;
  durationMs: number;
}

export type ContentBlockType = string;

export interface Conversation {
  id: string;
  title: string;
  workspaceId: string;
  updatedAt: string;
  permissionMode: PermissionMode;
  completedRunId?: string;
  unread?: boolean;
}

export interface CostReport {
  total: number;
  runTotal: number;
  requestCount: number;
  unknownRequests: number;
  runRequests: number;
  runUnknownRequests: number;
  unavailable?: boolean;
  currency: string;
  estimated: boolean;
  requests: (RequestCost)[] | null;
}

export interface CostSummary {
  total: number;
  runTotal: number;
  requestCount: number;
  unknownRequests: number;
  runRequests: number;
  runUnknownRequests: number;
  unavailable?: boolean;
}

export interface CustomConnectionInput {
  id: string;
  name: string;
  baseUrl: string;
  api: Api;
  apiKey: string;
  models: (ModelsJsonModel)[] | null;
}

export interface Draft {
  text: string;
  revision: number;
}

export interface DraftInput {
  id?: string;
  workspaceId?: string;
  text: string;
  revision: number;
}

export interface DraftScope {
  id?: string;
  workspaceId?: string;
}

export type EmptyInput = Record<string, never>;

export interface ErrorResponse {
  error: string;
}

export interface Failure {
  kind: string;
  message: string;
  advice: string;
  canContinue: boolean;
}

export interface FileInput {
  kind: string;
  id?: string;
  workspaceId?: string;
  path: string;
  action: string;
}

export interface HistoryNode {
  id: string;
  parentId: string;
  role: string;
  text: string;
  active: boolean;
}

export interface IDInput {
  id: string;
}

export interface ImageContent {
  type: ContentBlockType;
  data: string;
  mimeType: string;
}

export interface ImageQuery {
  id: string;
  message: string;
  index: number;
}

export interface InstructionResource {
  content: string;
  name: string;
  path: string;
}

export interface LoginOption {
  id: string;
  label: string;
}

export interface LoginStatus {
  id: string;
  provider: string;
  phase: string;
  message: string;
  url?: string;
  code?: string;
  prompt?: string;
  promptType?: string;
  options?: (LoginOption)[];
}

export interface MCPInput {
  oauth: boolean;
  oauthClientId?: string;
  oauthScope?: string;
  name: string;
  type: string;
  url?: string;
  command?: string;
  args: (string)[] | null;
  bearerToken?: string;
  clearBearerToken?: boolean;
  enabled: boolean;
  env?: Record<string, string>;
  clearEnv?: boolean;
}

export interface MCPServerView {
  oauth: boolean;
  signedIn: boolean;
  oauthClientId?: string;
  oauthScope?: string;
  name: string;
  type: string;
  url?: string;
  command?: string;
  args: (string)[] | null;
  enabled: boolean;
  hasBearerToken: boolean;
  status: string;
  toolCount: number;
  error?: string;
  envKeys: (string)[] | null;
}

export interface Message {
  id: string;
  role: string;
  text: string;
  toolName?: string;
  toolCallId?: string;
  status?: string;
  images?: (MessageImage)[];
  branchNodeId?: string;
  command?: CommandDetails;
}

export interface MessageImage {
  index: number;
  mimeType: string;
}

export interface ModelCatalog {
  providers: (ProviderChoice)[] | null;
  models: (ModelChoice)[] | null;
  source: string;
}

export interface ModelChoice {
  id: string;
  name: string;
  provider: string;
  api: string;
  supportsImages: boolean;
  contextWindow: number;
  maxTokens: number;
  thinkingLevels: (string)[] | null;
}

export interface ModelCost {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  tiers?: (ModelCostTier)[];
}

export interface ModelCostTier {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  inputTokensAbove: number;
}

export interface ModelImageInputLimits {
  resize?: ModelImageResizeOptions;
  maxPerMessage?: number;
  maxPerRequest?: number;
}

export interface ModelImageResizeOptions {
  maxWidth?: number;
  maxHeight?: number;
  maxBytes?: number;
  jpegQuality?: number;
}

export interface ModelInputLimits {
  maxRequestBytes?: number;
  images?: ModelImageInputLimits;
}

export type ModelInputModality = string;

export interface ModelPromptCache {
  short?: number;
  long?: number;
}

export interface ModelSelectionInput {
  provider: string;
  model: string;
  thinkingLevel: string;
}

export interface ModelsJsonModel {
  id: string;
  name?: string;
  api?: Api;
  baseUrl?: string;
  reasoning?: boolean;
  thinkingLevelMap?: ThinkingLevelMap;
  input?: (ModelInputModality)[];
  inputLimits?: ModelInputLimits;
  cost?: ModelCost;
  promptCache?: ModelPromptCache;
  contextWindow?: number;
  maxTokens?: number;
  samplingParams?: Record<string, unknown>;
  headers?: Record<string, string>;
  compat?: unknown;
}

export interface ModelsQuery {
  provider?: string;
}

export interface NameInput {
  name: string;
}

export interface NativeMenuStateInput {
  ready: boolean;
  busy: boolean;
  modal: boolean;
  workspaceId: string;
  activeId: string;
}

export interface NativeResponse {
  native: boolean;
}

export interface OAuthAnswerInput {
  id: string;
  answer: string;
}

export interface OKResponse {
  ok: boolean;
}

export interface PathInput {
  path: string;
}

export interface PathResponse {
  path: string;
}

export type PermissionMode = "ask" | "workspace-write" | "full-access";

export interface PermissionsInput {
  id: string;
  mode: PermissionMode;
}

export interface ProviderChoice {
  oauth: boolean;
  apiKeySupported: boolean;
  signedIn: boolean;
  custom: boolean;
  id: string;
  name: string;
  baseUrl: string;
  hasApiKey: boolean;
  hasSavedKey: boolean;
  model?: string;
  thinkingLevel?: string;
}

export interface ProviderConnectionInput {
  provider: string;
  baseUrl: string;
  apiKey?: string;
  clearApiKey?: boolean;
}

export interface ProviderInput {
  provider: string;
}

export interface QueueInput {
  id: string;
  text: string;
  mode?: string;
  images?: (ImageContent)[];
}

export type QueueMode = string;

export interface QueueMutationInput {
  id: string;
  messageId: string;
  text?: string;
}

export interface QueuedMessage {
  id: string;
  text: string;
  mode: QueueMode;
  imageCount?: number;
}

export interface ReadInput {
  id: string;
  runId: string;
}

export interface RemoveWorkspaceInput {
  id: string;
  conversationCount: number | null;
}

export interface RenameInput {
  id: string;
  title: string;
}

export interface RequestCost {
  id: string;
  runId: string;
  time: string;
  provider: string;
  providerName?: string;
  model: string;
  modelName?: string;
  purpose: string;
  status: string;
  usage: Usage;
  price: ModelCost;
  source: string;
  known: boolean;
}

export interface ResourceContentResponse {
  content: string;
}

export interface ResourceInput {
  workspaceId: string;
  kind: string;
  name: string;
  path: string;
  content: string;
  remove: boolean;
}

export interface ResourceInventory {
  workspaceId: string;
  instructions: (InstructionResource)[] | null;
  skills: (SkillResource)[] | null;
  templates: (SkillResource)[] | null;
  diagnostics: (string)[] | null;
}

export interface ResourceQuery {
  workspaceId: string;
  path: string;
}

export interface RunSummary {
  conversationId: string;
  workspaceId: string;
  phase: string;
  needsApproval: boolean;
}

export interface RunUsage {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  total: number;
}

export interface RuntimeStatus {
  runId?: string;
  provider?: string;
  thinkingLevel?: string;
  phase: string;
  model: string;
  usage: RunUsage;
  cost: CostSummary;
  timing: TaskTiming;
  contextTokens: number;
  contextWindow: number;
  compactions: number;
  toolFailures: number;
  updatedAt?: string;
}

export interface SendInput {
  id: string;
  text: string;
  images?: (ImageContent)[];
}

export interface Settings {
  provider: string;
  modelName: string;
  thinkingLevel: string;
  thinkingLevels: (string)[] | null;
  baseUrl: string;
  model: string;
  hasConnections: boolean;
  hasApiKey: boolean;
  appearance: AppearanceMode;
  supportsImages: boolean;
  imageUploadLimit: number;
}

export interface SkillResource {
  name: string;
  path: string;
  description: string;
}

export interface State {
  login?: LoginStatus;
  settings: Settings;
  workspaces: (Workspace)[] | null;
  conversations: (Conversation)[] | null;
  activeId: string;
  runs: (RunSummary)[] | null;
  messages: (Message)[] | null;
  queuedMessages: (QueuedMessage)[] | null;
  running: boolean;
  pendingApproval?: Approval;
  error?: string;
  runtime: RuntimeStatus;
  failure?: Failure;
}

export interface TaskTiming {
  startedAt?: string;
  elapsedMs: number;
  outputTokens: number;
  partial?: boolean;
}

export interface TextInput {
  text: string;
}

export type ThinkingLevelMap = Record<string, string | null> | null;

export interface Usage {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  cacheWrite1h?: number;
  reasoning?: number;
  totalTokens: number;
  cost: UsageCost;
}

export interface UsageCost {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  total: number;
}

export interface Workspace {
  id: string;
  name: string;
  path: string;
}

export interface WorkspaceInput {
  workspaceId: string;
}

export interface WorkspaceReferencesInput {
  workspaceId: string;
  paths: (string)[] | null;
}

export interface WorkspaceReferencesResponse {
  paths: (string)[] | null;
}

export interface WorkspaceResponse {
  ok: boolean;
  workspace: Workspace;
}

export interface ReadContracts {
  "/api/state": { input: EmptyInput; output: State };
  "/api/history": { input: IDInput; output: (HistoryNode)[] | null };
  "/api/costs": { input: IDInput; output: CostReport };
  "/api/resource-content": { input: ResourceQuery; output: ResourceContentResponse };
  "/api/custom-connection": { input: IDInput; output: CustomConnectionInput };
  "/api/models": { input: ModelsQuery; output: ModelCatalog };
  "/api/resources": { input: WorkspaceInput; output: ResourceInventory };
  "/api/artifacts": { input: IDInput; output: (Artifact)[] | null };
  "/api/artifact-preview": { input: ArtifactQuery; output: ArtifactPreview };
  "/api/draft": { input: DraftScope; output: Draft };
  "/api/mcp": { input: EmptyInput; output: (MCPServerView)[] | null };
}

export interface MutationContracts {
  "/api/config": { input: ConfigInput; output: OKResponse };
  "/api/appearance": { input: AppearanceInput; output: OKResponse };
  "/api/workspaces": { input: PathInput; output: WorkspaceResponse };
  "/api/conversations": { input: WorkspaceInput; output: OKResponse };
  "/api/open": { input: IDInput; output: OKResponse };
  "/api/read": { input: ReadInput; output: OKResponse };
  "/api/send": { input: SendInput; output: OKResponse };
  "/api/abort": { input: IDInput; output: OKResponse };
  "/api/approval": { input: ApprovalInput; output: OKResponse };
  "/api/permissions": { input: PermissionsInput; output: OKResponse };
  "/api/pick-workspace": { input: EmptyInput; output: PathResponse };
  "/api/workspace-references": { input: WorkspaceReferencesInput; output: WorkspaceReferencesResponse };
  "/api/copy-text": { input: TextInput; output: OKResponse };
  "/api/draft": { input: DraftInput; output: Draft };
  "/api/custom-connection": { input: CustomConnectionInput; output: OKResponse };
  "/api/remove-model-connection": { input: IDInput; output: OKResponse };
  "/api/resource": { input: ResourceInput; output: OKResponse };
  "/api/branch": { input: BranchInput; output: OKResponse };
  "/api/compact": { input: IDInput; output: OKResponse };
  "/api/oauth/start": { input: ProviderInput; output: OKResponse };
  "/api/oauth/answer": { input: OAuthAnswerInput; output: OKResponse };
  "/api/oauth/cancel": { input: EmptyInput; output: OKResponse };
  "/api/oauth/logout": { input: ProviderInput; output: OKResponse };
  "/api/provider-config": { input: ProviderConnectionInput; output: OKResponse };
  "/api/test-provider-connection": { input: ProviderConnectionInput; output: ConnectionTest };
  "/api/model-selection": { input: ModelSelectionInput; output: OKResponse };
  "/api/test-connection": { input: ConfigInput; output: ConnectionTest };
  "/api/continue": { input: IDInput; output: OKResponse };
  "/api/diagnostics": { input: EmptyInput; output: NativeResponse };
  "/api/export": { input: IDInput; output: NativeResponse };
  "/api/queue": { input: QueueInput; output: OKResponse };
  "/api/queue/edit": { input: QueueMutationInput; output: OKResponse };
  "/api/queue/delete": { input: QueueMutationInput; output: OKResponse };
  "/api/queue/steer": { input: QueueMutationInput; output: OKResponse };
  "/api/rename": { input: RenameInput; output: OKResponse };
  "/api/delete-conversation": { input: IDInput; output: OKResponse };
  "/api/remove-workspace": { input: RemoveWorkspaceInput; output: OKResponse };
  "/api/create-instructions": { input: WorkspaceInput; output: PathResponse };
  "/api/file": { input: FileInput; output: OKResponse };
  "/api/mcp/oauth/start": { input: NameInput; output: OKResponse };
  "/api/mcp/oauth/logout": { input: NameInput; output: OKResponse };
  "/api/mcp/save": { input: MCPInput; output: OKResponse };
  "/api/mcp/remove": { input: NameInput; output: OKResponse };
  "/api/mcp/connect": { input: EmptyInput; output: OKResponse };
  "/api/mcp/disconnect": { input: EmptyInput; output: OKResponse };
  "/api/native-menu-state": { input: NativeMenuStateInput; output: OKResponse };
}

export interface DownloadContracts {
  "/api/diagnostics": EmptyInput;
  "/api/export": IDInput;
  "/api/image": ImageQuery;
}

export interface StreamContracts {
  "/api/socket": State;
  "/api/events": State;
}

export const readPaths = ["/api/state", "/api/history", "/api/costs", "/api/resource-content", "/api/custom-connection", "/api/models", "/api/resources", "/api/artifacts", "/api/artifact-preview", "/api/draft", "/api/mcp"] as const;
export const mutationPaths = ["/api/config", "/api/appearance", "/api/workspaces", "/api/conversations", "/api/open", "/api/read", "/api/send", "/api/abort", "/api/approval", "/api/permissions", "/api/pick-workspace", "/api/workspace-references", "/api/copy-text", "/api/draft", "/api/custom-connection", "/api/remove-model-connection", "/api/resource", "/api/branch", "/api/compact", "/api/oauth/start", "/api/oauth/answer", "/api/oauth/cancel", "/api/oauth/logout", "/api/provider-config", "/api/test-provider-connection", "/api/model-selection", "/api/test-connection", "/api/continue", "/api/diagnostics", "/api/export", "/api/queue", "/api/queue/edit", "/api/queue/delete", "/api/queue/steer", "/api/rename", "/api/delete-conversation", "/api/remove-workspace", "/api/create-instructions", "/api/file", "/api/mcp/oauth/start", "/api/mcp/oauth/logout", "/api/mcp/save", "/api/mcp/remove", "/api/mcp/connect", "/api/mcp/disconnect", "/api/native-menu-state"] as const;
