// contractgen generates the frontend JSON contract from the Go wire types.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"github.com/minifish-org/pith-desk/internal/desk"
	"github.com/minifish-org/pith-desk/internal/wire"
)

func main() {
	check := flag.Bool("check", false, "fail if the checked-in contract has drifted")
	flag.Parse()
	if err := run(*check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(check bool) error {
	if err := verifyHandlers("internal/host", wire.Endpoints); err != nil {
		return err
	}
	data, err := generate(wire.Endpoints)
	if err != nil {
		return err
	}
	path := "frontend/src/contract.generated.ts"
	if check {
		saved, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Equal(saved, data) {
			return fmt.Errorf("Go/TypeScript contract drift: run npm run generate:contract")
		}
		fmt.Println("Go/TypeScript contract and host routes match")
		return nil
	}
	return os.WriteFile(path, data, 0644)
}

type generator struct {
	types map[string]reflect.Type
	err   error
}

func generate(endpoints []wire.Endpoint) ([]byte, error) {
	g := &generator{types: map[string]reflect.Type{}}
	for _, endpoint := range endpoints {
		for _, typ := range []reflect.Type{endpoint.Input, endpoint.Query, endpoint.Output} {
			if typ != nil {
				g.typeName(typ, false)
			}
		}
	}
	g.typeName(reflect.TypeFor[wire.ErrorResponse](), false)
	var output strings.Builder
	output.WriteString("// Code generated by cmd/contractgen. DO NOT EDIT.\n// HTTP authorization and WebSocket transport remain owned by the host/client.\n\n")
	names := make([]string, 0, len(g.types))
	for name := range g.types {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		typ := g.types[name]
		if typ.Kind() == reflect.Struct && len(jsonFields(typ)) == 0 {
			fmt.Fprintf(&output, "export type %s = Record<string, never>;\n\n", name)
			continue
		}
		if typ.Kind() != reflect.Struct {
			value := g.scalar(typ)
			if typ == reflect.TypeFor[desk.AppearanceMode]() {
				value = quotedUnion(string(desk.AppearanceSystem), string(desk.AppearanceLight), string(desk.AppearanceDark))
			}
			if typ == reflect.TypeFor[desk.PermissionMode]() {
				value = quotedUnion(string(desk.PermissionAsk), string(desk.PermissionWorkspaceWrite), string(desk.PermissionFullAccess))
			}
			fmt.Fprintf(&output, "export type %s = %s;\n\n", name, value)
			continue
		}
		fmt.Fprintf(&output, "export interface %s {\n", name)
		for _, field := range jsonFields(typ) {
			optional := ""
			if field.optional {
				optional = "?"
			}
			fmt.Fprintf(&output, "  %s%s: %s;\n", field.name, optional, g.typeName(field.typ, field.optional))
		}
		output.WriteString("}\n\n")
	}
	// Paths select both the input and output; callers cannot invent a response T.
	for _, method := range []string{"GET", "POST"} {
		name := "ReadContracts"
		if method == "POST" {
			name = "MutationContracts"
		}
		fmt.Fprintf(&output, "export interface %s {\n", name)
		for _, endpoint := range endpoints {
			if endpoint.Method != method || endpoint.Format != "json" {
				continue
			}
			input := endpoint.Query
			if method == "POST" {
				input = endpoint.Input
			}
			fmt.Fprintf(&output, "  %s: { input: %s; output: %s };\n", strconv.Quote(endpoint.Path), g.typeName(input, false), g.typeName(endpoint.Output, false))
		}
		output.WriteString("}\n\n")
	}
	output.WriteString("export interface DownloadContracts {\n")
	for _, endpoint := range endpoints {
		if endpoint.Format != "blob" {
			continue
		}
		query := "EmptyInput"
		if endpoint.Query != nil {
			query = g.typeName(endpoint.Query, false)
		}
		fmt.Fprintf(&output, "  %s: %s;\n", strconv.Quote(endpoint.Path), query)
	}
	output.WriteString("}\n\nexport interface StreamContracts {\n")
	for _, endpoint := range endpoints {
		if endpoint.Format == "stream" {
			fmt.Fprintf(&output, "  %s: %s;\n", strconv.Quote(endpoint.Path), g.typeName(endpoint.Output, false))
		}
	}
	output.WriteString("}\n\nexport const readPaths = [")
	var paths []string
	for _, endpoint := range endpoints {
		if endpoint.Method == "GET" && endpoint.Format == "json" {
			paths = append(paths, strconv.Quote(endpoint.Path))
		}
	}
	output.WriteString(strings.Join(paths, ", "))
	output.WriteString("] as const;\n")
	output.WriteString("export const mutationPaths = [")
	paths = nil
	for _, endpoint := range endpoints {
		if endpoint.Method == "POST" && endpoint.Format == "json" {
			paths = append(paths, strconv.Quote(endpoint.Path))
		}
	}
	output.WriteString(strings.Join(paths, ", "))
	output.WriteString("] as const;\n")
	if g.err != nil {
		return nil, g.err
	}
	return []byte(output.String()), nil
}

func quotedUnion(values ...string) string {
	for i, value := range values {
		values[i] = strconv.Quote(value)
	}
	return strings.Join(values, " | ")
}

type jsonField struct {
	name     string
	typ      reflect.Type
	optional bool
}

func jsonFields(typ reflect.Type) []jsonField {
	var result []jsonField
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		embedded := field.Type
		if embedded.Kind() == reflect.Pointer {
			embedded = embedded.Elem()
		}
		if field.PkgPath != "" && !(field.Anonymous && embedded.Kind() == reflect.Struct) {
			continue
		}
		parts := strings.Split(field.Tag.Get("json"), ",")
		if parts[0] == "-" {
			continue
		}
		if field.Anonymous && parts[0] == "" {
			result = append(result, jsonFields(embedded)...)
			continue
		}
		name := parts[0]
		if name == "" {
			name = field.Name
		}
		optional := false
		for _, part := range parts[1:] {
			optional = optional || part == "omitempty" || part == "omitzero"
		}
		result = append(result, jsonField{name: name, typ: field.Type, optional: optional})
	}
	return result
}

func (g *generator) typeName(typ reflect.Type, omitted bool) string {
	if typ == nil {
		return "EmptyInput"
	}
	if typ == reflect.TypeFor[json.RawMessage]() {
		return "unknown"
	}
	if typ.Kind() == reflect.Pointer {
		value := g.typeName(typ.Elem(), false)
		if !omitted {
			value += " | null"
		}
		return value
	}
	if typ.Name() != "" && typ.PkgPath() != "" {
		name := typ.Name()
		if old, exists := g.types[name]; exists {
			if old != typ {
				g.err = fmt.Errorf("ambiguous contract type name %s", name)
			}
			return name
		}
		g.types[name] = typ
		if typ.Kind() == reflect.Struct {
			for _, field := range jsonFields(typ) {
				g.typeName(field.typ, field.optional)
			}
		} else if typ.Kind() == reflect.Map || typ.Kind() == reflect.Slice || typ.Kind() == reflect.Array {
			g.typeName(typ.Elem(), false)
		}
		return name
	}
	switch typ.Kind() {
	case reflect.Slice, reflect.Array:
		value := "(" + g.typeName(typ.Elem(), false) + ")[]"
		if typ.Kind() == reflect.Slice && !omitted {
			value += " | null"
		}
		return value
	case reflect.Map:
		return "Record<string, " + g.typeName(typ.Elem(), false) + ">" + map[bool]string{true: "", false: " | null"}[omitted]
	case reflect.Struct:
		var fields []string
		for _, field := range jsonFields(typ) {
			mark := ""
			if field.optional {
				mark = "?"
			}
			fields = append(fields, field.name+mark+": "+g.typeName(field.typ, field.optional))
		}
		return "{ " + strings.Join(fields, "; ") + " }"
	default:
		return g.scalar(typ)
	}
}

func (g *generator) scalar(typ reflect.Type) string {
	switch typ.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Interface:
		return "unknown"
	case reflect.Map:
		return "Record<string, " + g.typeName(typ.Elem(), false) + "> | null"
	case reflect.Slice, reflect.Array:
		return "(" + g.typeName(typ.Elem(), false) + ")[] | null"
	default:
		g.err = fmt.Errorf("unsupported JSON contract type %s", typ)
		return "never"
	}
}

// Verify all actual /api paths and the declarations passed to Decode. A new
// handler cannot silently escape the registry just because it was not listed.
func verifyHandlers(directory string, endpoints []wire.Endpoint) error {
	registered := map[string]wire.Endpoint{}
	for _, endpoint := range endpoints {
		key := endpoint.Method + " " + endpoint.Path
		if _, exists := registered[key]; exists {
			return fmt.Errorf("duplicate contract %s", key)
		}
		registered[key] = endpoint
	}
	files, err := parser.ParseDir(token.NewFileSet(), directory, func(info os.FileInfo) bool { return !strings.HasSuffix(info.Name(), "_test.go") }, 0)
	if err != nil {
		return err
	}
	aliases := map[string]string{}
	for _, pkg := range files {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(node ast.Node) bool {
				if spec, ok := node.(*ast.TypeSpec); ok && spec.Assign.IsValid() {
					aliases[spec.Name.Name] = exprName(spec.Type, aliases)
				}
				return true
			})
		}
	}
	observed := map[string]bool{}
	var errors []string
	for _, pkg := range files {
		for path, file := range pkg.Files {
			ast.Inspect(file, func(node ast.Node) bool {
				literal, ok := node.(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					return true
				}
				value, _ := strconv.Unquote(literal.Value)
				if !strings.HasPrefix(value, "/api/") || strings.HasSuffix(value, "/") {
					return true
				}
				found := false
				for _, endpoint := range registered {
					if endpoint.Path == value {
						found = true
					}
				}
				if !found {
					errors = append(errors, fmt.Sprintf("%s: unregistered host route %s", filepath.Base(path), value))
				}
				return true
			})
			for _, declaration := range file.Decls {
				function, ok := declaration.(*ast.FuncDecl)
				if !ok || function.Body == nil {
					continue
				}
				if function.Name.Name == "serve" {
					ast.Inspect(function.Body, func(node ast.Node) bool {
						statement, ok := node.(*ast.IfStmt)
						if !ok {
							return true
						}
						var route, method string
						ast.Inspect(statement.Cond, func(node ast.Node) bool {
							if literal, ok := node.(*ast.BasicLit); ok && literal.Kind == token.STRING {
								value, _ := strconv.Unquote(literal.Value)
								if strings.HasPrefix(value, "/api/") && !strings.HasSuffix(value, "/") {
									route = value
								}
							}
							if selector, ok := node.(*ast.SelectorExpr); ok {
								switch selector.Sel.Name {
								case "MethodGet":
									method = "GET"
								case "MethodPost":
									method = "POST"
								}
							}
							return true
						})
						if route != "" && method != "" {
							key := method + " " + route
							if _, exists := registered[key]; !exists {
								errors = append(errors, "missing contract for "+key)
							}
							observed[key] = true
						}
						return true
					})
				}
				ast.Inspect(function.Body, func(node ast.Node) bool {
					clause, ok := node.(*ast.CaseClause)
					if !ok {
						return true
					}
					var routes []string
					for _, item := range clause.List {
						if literal, ok := item.(*ast.BasicLit); ok && literal.Kind == token.STRING {
							path, _ := strconv.Unquote(literal.Value)
							if strings.HasPrefix(path, "/api/") {
								routes = append(routes, path)
							}
						}
					}
					if len(routes) == 0 {
						return true
					}
					method := "POST"
					if function.Name.Name == "serveFeatureRead" {
						method = "GET"
					}
					var input string
					var query string
					ast.Inspect(clause, func(node ast.Node) bool {
						if spec, ok := node.(*ast.ValueSpec); ok {
							for _, name := range spec.Names {
								if name.Name == "in" {
									input = exprName(spec.Type, aliases)
								}
							}
						}
						if call, ok := node.(*ast.CallExpr); ok {
							if indexed, ok := call.Fun.(*ast.IndexExpr); ok {
								if selector, ok := indexed.X.(*ast.SelectorExpr); ok && selector.Sel.Name == "ReadQuery" {
									query = exprName(indexed.Index, aliases)
								}
							}
						}
						return true
					})
					for _, route := range routes {
						key := method + " " + route
						endpoint, exists := registered[key]
						if !exists {
							errors = append(errors, fmt.Sprintf("missing contract for %s %s", method, route))
							continue
						}
						observed[key] = true
						if input != "" && endpoint.Input != nil && input != goName(endpoint.Input) {
							errors = append(errors, fmt.Sprintf("request type drift for %s: handler %s, registry %s", route, input, goName(endpoint.Input)))
						}
						if endpoint.Query != nil && endpoint.Query.NumField() > 0 && query != goName(endpoint.Query) {
							errors = append(errors, fmt.Sprintf("query type drift for %s: handler %s, registry %s", route, query, goName(endpoint.Query)))
						}
					}
					return true
				})
				// Delegated handlers (file references and native menus) validate
				// their literal route with the same Decode helper.
				var input string
				ast.Inspect(function.Body, func(node ast.Node) bool {
					if spec, ok := node.(*ast.ValueSpec); ok {
						for _, name := range spec.Names {
							if name.Name == "in" {
								input = exprName(spec.Type, aliases)
							}
						}
					}
					call, ok := node.(*ast.CallExpr)
					if !ok || len(call.Args) < 3 {
						return true
					}
					selector, ok := call.Fun.(*ast.SelectorExpr)
					if !ok || selector.Sel.Name != "Decode" {
						return true
					}
					literal, ok := call.Args[0].(*ast.BasicLit)
					if !ok {
						return true
					}
					route, _ := strconv.Unquote(literal.Value)
					if endpoint, exists := registered["POST "+route]; exists && input != goName(endpoint.Input) {
						errors = append(errors, fmt.Sprintf("request type drift for %s: handler %s, registry %s", route, input, goName(endpoint.Input)))
					}
					return true
				})
			}
		}
	}
	for key := range registered {
		if !observed[key] {
			errors = append(errors, "contract has no host route: "+key)
		}
	}
	if len(errors) > 0 {
		sort.Strings(errors)
		return fmt.Errorf("host contract drift:\n%s", strings.Join(errors, "\n"))
	}
	return nil
}

func exprName(expression ast.Expr, aliases map[string]string) string {
	switch expression := expression.(type) {
	case *ast.SelectorExpr:
		if pkg, ok := expression.X.(*ast.Ident); ok {
			return pkg.Name + "." + expression.Sel.Name
		}
	case *ast.Ident:
		if name, ok := aliases[expression.Name]; ok {
			return name
		}
		return expression.Name
	}
	return "anonymous"
}
func goName(typ reflect.Type) string { return filepath.Base(typ.PkgPath()) + "." + typ.Name() }
